### ISSUE TITLE
支持C++函数的hook吗 

### ISSUE THREAD

**Issue by theochen2076** [bytedance/bhook#10]
想hook libDexFile.so 中 Dex相关的函数，但是用了C++的几个导出符号，都没有hook上，不知道是不是我调用的问题

**Comment by caikelun** [comment]
可以hook c++函数。在PLT和动态链接上，C函数和C++函数没有区别。需要注意下C++函数的符号编码（c++ mangler）和调用规则（类成员函数的第一个参数需要传this）。

**Comment by chongbo2013** [comment]
![image](https://user-images.githubusercontent.com/3191545/135460514-3cfd52af-af73-41d3-8ce6-23afc6648865.png)
你好 如果是一个指针函数  void *malloc; 如何修改调用BYTEHOOK_CALL_PREV   Called object type 'decltype(&((libWrapper->malloc)))' (aka 'void **') is not a function or function pointe

**Comment by theochen2076** [comment]
我试过C++的导出符号，貌似不行， 可能是我调用有问题，我再看下，多谢
