### ISSUE TITLE
可以支持下armeabi吗，发现目前还是有很多存量armeabi

### ISSUE THREAD

**Issue by chongbo2013** [bytedance/bhook#12]
可以支持下armeabi吗，发现目前还是有很多存量armeabi

**Comment by chongbo2013** [comment]
@caikelun 以前的项目都是armeabi ,基本不整armeabi-v7a 这样覆盖兼容的机子多，所以还是蛮需要的

**Comment by caikelun** [comment]
如果是打包的需要，你可以把armeabi-v7a的so放到armeabi目录中。线上实际上已经没有仅支持armeabi的32位arm了。

**Comment by chongbo2013** [comment]
@caikelun 大佬真的有很多app 都还是armeabi的，armeabi兼容armeabi-v7a，所以大部分就只放armeabi和arm64
![image](https://user-images.githubusercontent.com/3191545/137568185-e5f16dc6-d8b1-4e17-9ae5-e9efc2f29f26.png)
