### ISSUE TITLE
No signature of method

### ISSUE THREAD

**Issue by rookie-GS** [bytedance/bhook#14]
Build file 'D:\speed\bhook-main\bytehook\build.gradle' line: 5

A problem occurred evaluating project ':bytehook'.
> No signature of method: build_82d7azg7qimiazu2jjh6if0dz.android() is applicable for argument types: (build_82d7azg7qimiazu2jjh6if0dz$_run_closure1) values: [build_82d7azg7qimiazu2jjh6if0dz$_run_closure1@5fcfc7ad]

**Comment by caikelun** [comment]
建议检查一下编译环境。
