### ISSUE TITLE
大佬，请问下这个库如果想修改支持armeabi,大概要动哪几个地方

### ISSUE THREAD

**Issue by chongbo2013** [bytedance/bhook#15]
大佬请帮忙指导下，我看看能否修改下支持armeabi,我们32只支持armeabi，不支持armeabi-v7a，不然32位用不了

**Comment by caikelun** [comment]
现在较新版本NDK已经不支持armeabi了，而且从实际数据看，仅支持armeabi不支持armeabi-v7a的设备已经没有了。armeabi-v7a相对于armeabi，无论在动态库体积还是运行速度上都有优势。

你如果一定要用armeabi，可以自己降级NDK版本编译试试。

**Comment by chongbo2013** [comment]
是的，现在确实都是64了，但是部分32的用户还是很多，所以还是想支持下。谢了我先编译下





------------------ 原始邮件 ------------------
发件人: Kelun Cai ***@***.***&gt;
发送时间: 2021年11月12日 10:57
收件人: bytedance/bhook ***@***.***&gt;
抄送: ferris ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [bytedance/bhook] 大佬，请问下这个库如果想修改支持armeabi,大概要动哪几个地方 (Issue #15)





 
现在较新版本NDK已经不支持armeabi了，而且从实际数据看，仅支持armeabi不支持armeabi-v7a的设备已经没有了。armeabi-v7a相对于armeabi，无论在动态库体积还是运行速度上都有优势。
 
你如果一定要用armeabi，可以自己降级NDK版本编译试试。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by caikelun** [comment]
armeabi-v7a也是32位的。
