### ISSUE TITLE
是否可以对.init_array中的调用进行hook

### ISSUE THREAD

**Issue by yimun** [bytedance/bhook#18]
从原理上来看，bhook执行的时机应该是在dlopen之后？现在有个需求是：dlopen里会执行.init和.init_array区块的代码，我需要hook一个在.init_array区块中执行的函数，从本地尝试来看hook是无效的，原因是dlopen阶段hook还未执行，是否有其他办法可以做到呢？

![image](https://user-images.githubusercontent.com/4262706/144379849-b9f7e1f9-d521-4e71-99df-4c2cab074bd2.png)

**Comment by caikelun** [comment]
@yimun 是的，目前执行hook的时机是dlopen完成之后，所以.init和.init_array中的逻辑在执行时还没有hook。我有空想想怎么提前一下hook时机，有什么好的建议和想法欢迎一起探讨哈～

**Comment by fh2002** [comment]
[https://github.com/bytedance/bhook/issues/37#issuecomment-1097623212](url)
