### ISSUE TITLE
Android 11 没有命中自己App中加载的so

### ISSUE THREAD

**Issue by zqhGeek** [bytedance/bhook#36]
### bytehook Version

1.0.5

### Android OS Version

11

### Android ABIs

arm64-v8a

### Device Manufacturers and Models

oppo

### Describe the Bug

![df702b1fadb03cf625d6cb43ef172f1](https://user-images.githubusercontent.com/11883200/159691268-cb300a95-997c-4791-9140-3f3b9434c375.png)

我使用bhook去hook自己加载的另一个so，发现没有hook到，map中没找到这个so，pc命中的是base.apk，打印bhook中的bh_elf_manager_iterate_cb，没看到这个so，这个是Android 11的特性？

**Comment by zqhGeek** [comment]
感谢大佬的帮助，因为我习惯了看那个log中的 hook ok的日志，看到没打印就认为是不成功，没有用回调去看，实际看是hook成功了，我先关闭，后面我补上回调看看，结果

**Comment by caikelun** [comment]
@zqhGeek `adb logcat -b main -G 6M`

**Comment by zqhGeek** [comment]
我已经在开发者模式调到了16M，应该不是这个影响？

**Comment by zqhGeek** [comment]
@caikelun  我已经在开发者模式调到了16M，应该不是这个影响？
