### ISSUE TITLE
是否遗漏了self->cfi_hook_lock的destroy操作

### ISSUE THREAD

**Issue by Mr-JingShi** [bytedance/bhook#45]
### bytehook Version

1.0.0

### Android OS Version

10.0

### Android ABIs

armeabi-v7a

### Device Manufacturers and Models

Google Pixel 3

### Describe the Bug

https://github.com/bytedance/bhook/blob/8bb793317ba037e9aefcab1d2da8a8f0d94fde1e/bytehook/src/main/cpp/bh_elf.c#L283

老师你好，这个地方是否遗漏了self->cfi_hook_lock的destroy操作？

  pthread_mutex_destroy(&(*self)->hook_lock);
#ifdef __LP64__
  pthread_mutex_destroy(&(*self)->cfi_hook_lock);
#endif
  pthread_mutex_destroy(&(*self)->dyn_parse_lock);

**Comment by caikelun** [comment]
是的。感谢反馈，我们在下个版本修复。
