### ISSUE TITLE
鲜时光TV APK Android 13平台无法打开

### ISSUE THREAD

**Issue by liunanxuan** [bytedance/bhook#72]
### bytehook Version

1.0.0

### Android OS Version

13

### Android ABIs

armeabi-v7a, arm64-v8a

### Device Manufacturers and Models

Mediatek TV

### Describe the Bug

com.bytedance.mira.hook crash

04-12 02:17:35.776  6461  6461 I System.out: mira/activity: MiraInstrumentation execStartActivity handleException
04-12 02:17:35.785  6461  6461 W System.err: mira/activity: MiraInstrumentation execStartActivity error. null
04-12 02:17:35.785  6461  6461 W System.err: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.ixigua.android.tv.bestv/com.ixigua.tv.plugin.feed.home.view.HomeActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
04-12 02:17:35.785  6461  6461 W System.err: java.lang.reflect.Method.invoke(Native Method)
04-12 02:17:35.785  6461  6461 W System.err: com.bytedance.mira.util.MethodUtils.invokeMethod(SourceFile:161)
04-12 02:17:35.785  6461  6461 W System.err: com.bytedance.mira.hook.delegate.MiraInstrumentation.execStartActivity(SourceFile:165)
04-12 02:17:35.785  6461  6461 W System.err: android.app.Activity.startActivityForResult(Activity.java:5470)
04-12 02:17:35.785  6461  6461 W System.err: android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(SourceFile:54)
04-12 02:17:35.785  6461  6461 W System.err: android.support.v4.app.FragmentActivity.startActivityForResult(SourceFile:68)
04-12 02:17:35.785  6461  6461 W System.err: android.app.Activity.startActivityForResult(Activity.java:5428)
04-12 02:17:35.786  6461  6461 W System.err: android.support.v4.app.FragmentActivity.startActivityForResult(SourceFile:751)
04-12 02:17:35.786  6461  6461 W System.err: android.app.Activity.startActivity(Activity.java:5926)
04-12 02:17:35.786  6461  6461 W System.err: android.app.Activity.startActivity(Activity.java:5893)
04-12 02:17:35.786  6461  6461 W System.err: com.ixigua.tv.plugin.a.b.x30_a.f(SourceFile:274)
04-12 02:17:35.786  6461  6461 W System.err: com.ixigua.tv.plugin.a.b.x30_a.c(SourceFile:249)
04-12 02:17:35.786  6461  6461 W System.err: com.ixigua.tv.plugin.a.b.x30_a.a(SourceFile:128)
04-12 02:17:35.786  6461  6461 W System.err: com.ixigua.tv.plugin.a.b.x30_b.a(SourceFile:13)
04-12 02:17:35.786  6461  6461 W System.err: com.ixigua.tv.plugin.application.service.PluginService.onSplashCreate(SourceFile:93)
04-12 02:17:35.786  6461  6461 W System.err: com.ixigua.android.tv.module.home.view.MainActivity.a(SourceFile:103)
04-12 02:17:35.786  6461  6461 W System.err: com.ixigua.android.tv.service.launch.a.c(SourceFile:82)
04-12 02:17:35.786  6461  6461 W System.err: com.ixigua.android.tv.service.launch.a.a(SourceFile:34)
04-12 02:17:35.786  6461  6461 W System.err: com.ixigua.android.tv.module.home.view.MainActivity.onCreate(SourceFile:70)
04-12 02:17:35.786  6461  6461 W System.err: android.app.Activity.performCreate(Activity.java:8290)
04-12 02:17:35.786  6461  6461 W System.err: android.app.Activity.performCreate(Activity.java:8269)
04-12 02:17:35.787  6461  6461 W System.err: android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
04-12 02:17:35.787  6461  6461 W System.err: com.bytedance.mira.hook.delegate.MiraInstrumentation.callActivityOnCreate(SourceFile:385)
04-12 02:17:35.787  6461  6461 W System.err: android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
04-12 02:17:35.787  6461  6461 W System.err: android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
04-12 02:17:35.787  6461  6461 W System.err: android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
04-12 02:17:35.787  6461  6461 W System.err: android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
04-12 02:17:35.787  6461  6461 W System.err: android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
04-12 02:17:35.787  6461  6461 W System.err: android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
04-12 02:17:35.787  6461  6461 W System.err: android.os.Handler.dispatchMessage(Handler.java:106)
04-12 02:17:35.787  6461  6461 W System.err: android.os.Looper.loopOnce(Looper.java:201)
04-12 02:17:35.787  6461  6461 W System.err: android.os.Looper.loop(Looper.java:288)
04-12 02:17:35.787  6461  6461 W System.err: android.app.ActivityThread.main(ActivityThread.java:7898)
04-12 02:17:35.787  6461  6461 W System.err: java.lang.reflect.Method.invoke(Native Method)
04-12 02:17:35.787  6461  6461 W System.err: com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
04-12 02:17:35.787  6461  6461 W System.err: com.android.internal.os.ZygoteInit.main(ZygoteInit.java:938)

**Comment by caikelun** [comment]
`com.bytedance.mira.hook` 和 bytehook 没有关系，不是一个东西。建议直接联系“鲜时光app”反馈问题吧。
