### ISSUE TITLE
Building documentation instructions with mkdocs

### ISSUE THREAD

**Issue by 5peak2me** [bytedance/bhook#76]
### the Feature, Motivation and Pitch

I see that https://github.com/bytedance/bhook/tree/main/doc#readme has documentation on its use, and I was wondering if it would be possible to use workflow to create mkdocs sites to publish to the gh-pages branch so that we could have a properly documented site.

### Alternatives

![Snipaste_2023-08-02_21-25-32](https://github.com/bytedance/bhook/assets/6847158/8267375f-fa99-4327-bdc0-6a0d5cf84536)

**Comment by caikelun** [comment]
`doctree` and `outline` of github web can also meet the demand?

![11](https://github.com/bytedance/bhook/assets/102436/4a0ee184-22f5-4776-9b91-07b3cd55f339)

![22](https://github.com/bytedance/bhook/assets/102436/40b0564f-d07d-4a08-b59c-9a2b3f69f150)

**Comment by 5peak2me** [comment]
looks good.
