### ISSUE TITLE
模拟器hook失效

### ISSUE THREAD

**Issue by zhaowq32** [bytedance/bhook#8]
apk中仅有armv7-a的库，通过houdini加载后，bhook失效了。请问这个有解决方法么？

**Comment by caikelun** [comment]
houdini没有验证过，可能是bytehook中 trampoline的问题。可以试试在初始化时把bytehook设置成“手动模式”，这样不会有trampoline，可以试试。

**Comment by zhaowq32** [comment]
目前的解决方案是优先加载x86的动态库，如果加载失败了，再加载arm的。

**Comment by zhaowq32** [comment]
> 大佬能支持armeabi吗，工程里只不支持armeabi-v7a ![image](https://user-images.githubusercontent.com/15277653/137568132-f917c370-302e-4521-b46f-5c4dd4f03476.png)

armeabi-v7a的库拷贝到armeabi中应该就行吧，毕竟现在基本上不会有armeabi的手机了
