### ISSUE TITLE
在Android 7 对dlopen的监控会影响系统原本的dlopen调用导致后续的so都无法loading

### ISSUE THREAD

**Issue by zqhGeek** [bytedance/bhook#82]
### bytehook Version

1.0.8

### Android OS Version

7.1

### Android ABIs

armeabi-v7a

### Device Manufacturers and Models

模拟器

### Describe the Bug

只要监控dlopen后，就没法再dlopen其他so某些日志是我自己加上去的
![image](https://github.com/bytedance/bhook/assets/11883200/e395278e-34ab-40ce-a837-711c9282a530)

**Comment by zqhGeek** [comment]
测试了一下，本质应该是xdl那套方式在这种情况下不行，我尝试了使用xdl去dlopen so也是直接失败的

**Comment by zqhGeek** [comment]
![image](https://github.com/bytedance/bhook/assets/11883200/d2873052-36ba-43c7-9c59-bd4ae105b667)
我使用原始函数指针调用做兜底，不知道这样做是否会有坑，起码在这个模式中是正常的......

**Comment by Mr-JingShi** [comment]
请参考下：在夜神模拟器上跑armeabi-v7a包相关问题咨询 #91

**Comment by caikelun** [comment]
@zqhGeek bytehook不支持模拟器，没有在模拟器中做过任何测试。
