### ISSUE TITLE
华为MT7-TL10 hook失败

### ISSUE THREAD

**Issue by zhaowq32** [bytedance/bhook#9]
MainActivity为webview，加载网页时未hook掉connect函数。红米k20 pro及模拟器均正常hook。

**Comment by caikelun** [comment]
华为MT7-TL10上其他函数hook正常吗？hook执行流程不会对某个函数做区别对待。
可以分析下华为MT7-TL10 webview 执行 connect在哪个so，以及执行流程是否调用到了 connect（用readelf，objdump，ida等等）

**Comment by zhaowq32** [comment]
执行流程肯定是调用到了connect，因为我其他手机和模拟器均能走到替换函数内。

**Comment by caikelun** [comment]
可以注册hooked回调，来看下connect是否hook成功了。

**Comment by wustwg** [comment]
> MainActivity为webview，加载网页时未hook掉connect函数。红米k20 pro及模拟器均正常hook。

webview你确定能hook到？

**Comment by zhaowq32** [comment]
后续没有再使用，改用其他框架了。webview里的connect是可以被hook的
